### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by dido1998** [xrc10/formal-sty-trans#1]
```Traceback (most recent call last):
  File "train.py", line 469, in <module>
    main(args)
  File "train.py", line 181, in main
    trg_plain_epoch_iter=trg_plain_epoch_iter,
  File "train.py", line 241, in train
    for k, v in log_output.items():
```

I get this error while training (I ran pipeline.sh). `log_output` is None.  Can someone suggest what is wrong?

**Comment by wangruoyu1126** [comment]
I also got this, turns out that due to out of memory
